<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <GenerateDependencyFile>false</GenerateDependencyFile>
        <GenerateDocumentationFile>true</GenerateDocumentationFile>
        <RootNamespace>UnsafeUnityEnginePrivateAPI</RootNamespace>
        <DebugType>embedded</DebugType>
        <OutputPath>$(PackageDirectory)</OutputPath>
    </PropertyGroup>
    <ItemGroup>
        <ProjectReference Include="../UnityEngine/UnityEngine.csproj"  Private="False" />
    </ItemGroup>
	<ItemGroup>
		<AssemblyAttribute Include="System.Runtime.CompilerServices.IgnoresAccessChecksToAttribute">
			<_Parameter1>UnityEngine</_Parameter1>
		</AssemblyAttribute>
	</ItemGroup>
</Project>
